django/config/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

django/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
import core.urls
import user.urls
from user import views as user_views
from core.views import GeneratePdf, GeneratePdfHistorial

#con urlpatterns podemos mappear las urls de la pagina con sus respectivas vistas
urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(user.urls, namespace='user')),
    path('user/', include('django.contrib.auth.urls')),
    path('', include(core.urls, namespace='core')),
    
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        user_views.activate, name='activate'), #para el link de validacion del email

    path('pdf/consultas/', GeneratePdf.as_view(), name='get-pdf-consulta'),
    path('pdf/historial/', GeneratePdfHistorial.as_view(), name='get-pdf-historial'),
]

django/core/urls.py
from django.urls.conf import path
from core import views

app_name = 'core'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('history', views.MovementHistoryView.as_view(), name='mov_history'),
    path('accounts', views.CheckAccounts.as_view(), name='check_accounts'),
    path('transaction/new', views.TransactionView.as_view(), name='make_transaction'),
]

django/user/urls.py
from django.contrib.auth.views import LogoutView, LoginView #Dejaremos que django se haga cargo de las vistas para el manejo del
#login y el logout del usuario.
from django.urls import path
from user import views

app_name = 'user'
urlpatterns = [
    path('login', LoginView.as_view(), name="login"), #LoginView.as_view() es una vista que proporciona django
    path('logout', LogoutView.as_view(), name="logout"), #LogoutView.as_view() es una vista que proporciona django
    path('register', views.registrationFormExtended, name="register"),
    path('edit', views.edit_user_info, name="edit"),
]

django/core/models.py
from django.db import models

# Create your models here.

django/core/forms.py
from django import forms
from core.apis import make_transaction, get_accounts


class TransactionForm(forms.Form):
    issuer = forms.IntegerField()
    receiver = forms.IntegerField()
    amount = forms.FloatField()

    def __init__(self, *args, **kwargs):
        if len(args) > 0:
            self.user_core_id = args[len(args)-1]['user'].profile.core_id
        super(TransactionForm, self).__init__(*args, **kwargs)

    def is_valid(self):
        valid = super(TransactionForm, self).is_valid()
        if not valid:
            return valid

        issuer = self.cleaned_data['issuer']
        transaction_data = {
            'issuer': issuer,
            'receiver': self.cleaned_data['receiver'],
            'amount': self.cleaned_data['amount'],
        }

        # Check if issuer account belongs to user
        accounts_data = get_accounts(self.user_core_id)
        accounts_id = [account['NumeroCuenta']
                       for account in accounts_data
                       if 'NumeroCuenta' in account]

        if(issuer not in accounts_id):
            self.add_error('issuer', 'Cuenta no le pertenece')
            return False

        transaction = make_transaction(transaction_data)
        if transaction['exito']:
            return valid
        else:
            if transaction['codigo'] == -1:
                self.add_error('issuer', transaction['mensaje'])
            if transaction['codigo'] == -2:
                self.add_error('receiver', transaction['mensaje'])
            if transaction['codigo'] == -3:
                self.add_error('amount', transaction['mensaje'])
            return False

django/core/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from core.apis import get_client, get_accounts, get_account_movements, id_card_exists
from django.views.generic import FormView
from core.forms import TransactionForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import View
from .utils import render_to_pdf
from django.contrib.auth.decorators import login_required

from django.utils import timezone

#PARA GENERAR LOS REPORTES PDF

class GeneratePdfHistorial(View):

    def get(self, request, *args, **kwargs):
        ctx = {}
        User = request.user
        nombre_usuario = User.first_name
        apellidos_usuario = User.last_name
        cedula = User.profile.id_card
        fecha = (timezone.now)
        cedula1 = id_card_exists(cedula)
        id_core = cedula1['mensaje']
        accounts = get_accounts(id_core)
        ctx['accounts'] = {}
        totalmovs = 0
        for account in accounts:
            # print(account)
            account_mov = get_account_movements(account['NumeroCuenta'])
            ctx['accounts'].update({account['NumeroCuenta']: account_mov})
            totalmovs = totalmovs + 1
            ctx['totalmovs'] = totalmovs
            ctx['Fecha'] = fecha
            ctx['nombre'] = nombre_usuario
            ctx['apellido'] = apellidos_usuario
            print(ctx['accounts'])
        #haremos todos los request para conseguir las cuentas del cliente denuevo x
        pdf = render_to_pdf('core/pdf_historial.html', ctx)
        return HttpResponse(pdf, content_type='application/pdf')


class GeneratePdf(View):

    def get(self, request, *args, **kwargs):
        User = request.user
        nombre_usuario = User.first_name
        apellidos_usuario = User.last_name
        cedula = User.profile.id_card
        fecha = (timezone.now)
        cedula1 = id_card_exists(cedula)
        id_core = cedula1['mensaje']
        accounts = get_accounts(id_core)
        total_balance = 0
        for cuenta in accounts:
            total_balance = total_balance + cuenta['Saldo']
        ctx = {
            'accounts': accounts,
            'total_balances': total_balance,
            'Fecha': fecha,
            'nombre': nombre_usuario,
            'apellido': apellidos_usuario,
        }
        #haremos todos los request para conseguir las cuentas del cliente denuevo x
        pdf = render_to_pdf('core/pdf_consultas.html', ctx)
        return HttpResponse(pdf, content_type='application/pdf')


class CheckAccounts(LoginRequiredMixin, TemplateView):
    template_name = 'core/accounts.html'

    def get_context_data(self):
        ctx = super(CheckAccounts, self).get_context_data()
        core_id = self.request.user.profile.core_id
        ctx['client'] = get_client(self.request.user.profile.core_id)
        accounts = get_accounts(core_id)
        ctx['accounts'] = accounts
        total_balance = 0
        for cuenta in accounts:
            total_balance = total_balance + cuenta['Saldo']
        ctx['total_balances'] = total_balance
        return ctx

class HomeView(TemplateView):
    template_name = 'core/home.html'

    def get_context_data(self):
        ctx = super(HomeView, self).get_context_data()
        if self.request.user.is_authenticated:
            client_data = get_client(self.request.user.profile.core_id)
            ctx['client'] = client_data
        return ctx


class MovementHistoryView(LoginRequiredMixin, TemplateView):
    template_name = 'core/mov_history.html'

    def get_context_data(self):
        ctx = super(MovementHistoryView, self).get_context_data()
        core_id = self.request.user.profile.core_id
        client_data = get_client(core_id)
        ctx['client'] = client_data

        accounts_data = get_accounts(core_id)
        accounts_id = [account['NumeroCuenta']
                       for account in accounts_data
                       if 'NumeroCuenta' in account]

        ctx['accounts'] = {}
        for account in accounts_id:
            account_mov = get_account_movements(account)
            ctx['accounts'].update({account: account_mov})
        return ctx


class TransactionView(LoginRequiredMixin, FormView):
    form_class = TransactionForm
    template_name = 'core/transactions.html'

    def get_form(self):
        if self.request.method == "POST":
            user_data = {'user': self.request.user}
            return TransactionForm(self.request.POST, user_data)
        return TransactionForm

    def form_valid(self, form):
        message = "Transferencia realizada con exito"
        ctx = self.get_context_data()
        ctx['message'] = message
        return render(self.request, self.template_name, context=ctx)

django/core/templates/core/accounts.html
<!DOCTYPE html>
<html>
<head>
    <!-- start of    bootstrap section-->
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <!-- end of     bootstrap section -->

    <!-- Para usar los iconos de google-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


    <title> Consultar Cuentas </title>
</head>
<body>
    <!-- start of    bootstrap section-->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <!-- end of     bootstrap section -->   

<!-- Logo y seccion de Bienvenido-->

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
        <a class="navbar-brand" href="#">
            <img src="http://placehold.it/150x50?text=Logo" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">  </span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active"> 
                <i class="material-icons" style="font-size:36px; color: gray">person</i>
            </li>
            <li>
                <p class = "nav-link" style="color: white;"> {{user.first_name}} {{user.last_name}} </p>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="#">Consultar Cuentas</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'core:mov_history' %}"> Historial de transacciones </a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'core:make_transaction' %}"> Realizar Transacción </a>
            </li>
            <li class="nav-item">
                <div class = container style="padding-right: 1%;">
                    <a class="material-icons" style="font-size:36px;color: gray" href="{% url 'user:edit' %}"> settings </a>
                </div>
            </li>
            <li class="nav-item">
                <div class = container>
                    <a class="material-icons" style="font-size:36px;color: gray" href="{% url 'logout' %}"> exit_to_app </a>
                </div>
            </li>        
        </ul>
        </div>
    </div>
</nav>



<!-- FINAL DE Logo y seccion de Bienvenido-->

    <!-- Consultar Cuentas TABLA -->
    <div class="mx-auto" style="width: 1000px; padding-bottom: 5%; padding-top: 100px;" >
        <div class = "container" style="padding: 80px; border: 2px solid lightslategray; "> 
            <h1 class="display-4">Consultar Cuentas</h1>
            <hr> </hr>
            <p class="lead">
                    Estas son sus Cuentas activas en WaWaWanK. Haga click en Reporte PDF para general y descargar un Reporte
            </p>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Número de Cuenta</th>
                        <th scope="col">Tipo de Cuenta</th>
                        <th scope="col">Balance Disponible</th>
                    </tr>
                </thead>
                <tbody>
                    {% for account in accounts %}
                        <tr>
                          <th scope="row">-</th>
                          <td> {{ account.NumeroCuenta }} </th>
                          <td> {{ account.Tipo }} </th>
                          <td> {{ account.Saldo }} </th>
                        </tr>
                    {% endfor %}
                </tbody>
                    <tr style="background-color:lightsteelblue;">
                        <th scope="row" colspan="3"> Total </th>
                        <td scope="col" style="text-align:right;">Balance Total</td>
                    </tr>
                    <!-- Aqui se despliegan los totales -->
                    <tr>
                        <td scope="col" colspan="4" style="text-align:right;">{{ total_balances }}</td>
                    </tr>
            </table>
            <a href="{% url 'get-pdf-consulta' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true"> 
                <i class="material-icons" style="font-size:20px;color:white">file_download </i> Reporte PDF </a>
        </div>
    </div>
    <!-- FINAL de Consultar Cuentas TABLA -->

    <!-- Footer -->
    <footer class="page-footer font-small black">
        <div background-color = "blue">
        <!-- Copyright -->
        <div class=" kilimanjaro_bottom_header_one section_padding_50 text-center">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <p>© All Rights Reserved by WaWaWanK</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Copyright -->
        </div>
    </footer>
      <!-- Footer -->

</body>
</html>

django/core/templates/core/home.html
<!DOCTYPE html>
<html>
<head>
    <!-- start of    bootstrap section-->
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <!-- end of     bootstrap section -->

    <!-- Para usar los iconos de google-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <title> Principal </title>
    {% if user.is_authenticated %}

    {% else %}
    <style>
        .button {
            background-color: #984949;
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
            -webkit-transition-duration: 0.4s; /* Safari */
            transition-duration: 0.4s;
        }
        
        .button2:hover {
            box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
        }
        body {background-color: #3f576c;}
        a:link {
            text-decoration: none;
        }
        
        a:visited {
            text-decoration: none;
        }
        
        a:hover {
            text-decoration: none;
            background-color: white;
        }
        
        a:active {
            text-decoration: none;
        }
        .container2 {
            position: absolute;
            top: 25%;
            right: 80px;
            width: 40%;
            height: 50%;
            background-color: #DDDDDD;
        }
    </style>
    {% endif %}
</head>
<body>
    <!-- start of    bootstrap section-->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <!-- end of     bootstrap section -->   


{% if user.is_authenticated %}
<!-- Logo y seccion de Bienvenido-->
<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="http://placehold.it/150x50?text=Logo" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon">  </span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"> 
                    <i class="material-icons" style="font-size:36px; color: gray">person</i>
                </li>
                <li>
                    <p class = "nav-link" style="color: white;"> {{ client.Nombre }} {{ client.Apellido }} </p>
                </li>
                <li class="nav-item">
                    <div class = container>
                        <a class="material-icons" style="font-size:36px;color: gray" href="{% url 'logout' %}"> exit_to_app </a>
                    </div>
                </li>        
            </ul>
            </div>
        </div>
    </nav>

<!-- FINAL DE Logo y seccion de Bienvenido-->

    <!-- Menu de botones --> 
    <div class="mx-auto" style="width: 1500px; padding-bottom: 5%; padding-top: 100px;" >
        <div class = "container" style="padding: 80px; border: 2px solid lightslategray; "> 
            <div class = container style="padding-bottom: 25px;">
                    <h1 class="display-4"> ¡Bienvenido de nuevo {{ client.Nombre }} {{ client.Apellido }} a  WaWaWanKing!</h1> 
                    <p class="lead" style="padding-top: 25px;">
                            ¿Qué deseas hacer hoy?
                    </p> 
            </div>
            <a href="{% url 'core:check_accounts' %}" class="btn btn-light btn-lg btn-block" role="button"> Consultar Cuentas </a>
            <a href="{% url 'core:mov_history' %}" class="btn btn-secondary btn-lg btn-block" role="button"> Historial de Transacciones </a>
            <a href="% url 'core:make_transaction' %}" class="btn btn-light btn-lg btn-block" role="button"> Realizar Transacciones </a>
            <a href="{% url 'user:edit' %}" class="btn btn-secondary btn-lg btn-block" role="button"> Configurar Cuenta </a>
        </div>
    </div>
    <!-- FINAL del menu de botones -->

    {% else %}
          
    <div style="width: 100%; padding-bottom: 5%; padding-top: 100px;" >
            <div class = ".container-fluid" style="padding: 80px; width: 100%; border: 2px solid #f3e5e5; background-image: url('https://i.pinimg.com/originals/08/45/c1/0845c1b2846f5c429ba8169562bf2fc5.jpg')"> 
                <div style="width:40%; border: solid 1px gray;">
            <h3 class="display-1" style="font-weight: bold; text-align:center;"> Internet Banking </h3>
                    <p class="lead" style="margin:30px; text-align: center;">
                        Banco Miercoles (Banco 1).	
                    </p>
            </div>
            <div class="container2">
            <div style = "background-color: #a81311; width:100%; heigh: 100px; color:#a81311">
                lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum vlorem ipsum
                lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum vlorem ipsum
            </div>
            <a class="button button2" href="{% url 'login' %}" role="button" style="margin: 0 auto; width: 300px; display: flex; justify-content: center; font-family: Open Sans; font-size: 25px; border-radius: 12px; margin-top: 50px"> 
            Iniciar Sesión </a>
            <a class="button button2" href="{% url 'user:register' %}" role="button" style="margin: 0 auto; width: 300px; display: flex; justify-content: center; font-family: Open Sans; font-size: 25px; border-radius: 12px; margin-top: 30px"> 
            Registrarse </a>
            </div>
            </div>
        </div>
        {% endif %}

    <!-- Footer -->
    <footer class="page-footer font-small black">
        <div background-color = "blue">
        <!-- Copyright -->
        <div class=" kilimanjaro_bottom_header_one section_padding_50 text-center">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <p>© All Rights Reserved by WaWaWanK</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Copyright -->
        </div>
    </footer>
      <!-- Footer -->
</body>
</html>
   

django/core/templates/core/mov_history.html
{% extends 'base.html' %}

{% block title %}Historial de movimientos{% endblock title %}

{% block body %}
  <h1>Historial de movimientos</h1>

  {% for key, value in accounts.items %}
    <p>Cuenta: <span class="badge badge-secondary">{{ key }}</span></p>

    <table class="table table-striped">
      <thead>
        <th scope="col">Cuenta emisor</th>
        <th scope="col">Cuenta receptor</th>
        <th scope="col">Tipo de movimiento</th>
        <th scope="col">Monto</th>
        <th scope="col">Banco</th>
      </thead>
      <tbody>
        {% for movement in value %}
        <tr>
          <td>{{ movement.CuentaEmisor }}</th>
          <td>{{ movement.CuentaReceptor }}</th>
          <td>{{ movement.tipoMovimiento }}</th>
          <td>{{ movement.Monto }}</th>
          <td>{{ movement.Banco }}</th>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endfor %}

{% endblock body %}

django/core/templates/core/pdf_consultas.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Consulta de cuentas </title>
        <style type="text/css">
            body {
                font-weight: 200;
                font-size: 14px;
            }
            .header {
                font-size: 20px;
                font-weight: 100;
                text-align: center;
                color: #007cae;
            }
            .title {
                font-size: 22px;
                font-weight: 100;
               /* text-align: right;*/
               padding: 10px 20px 0px 20px;  
            }
            .title span {
                color: #007cae;
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                /*margin-left: 40%;*/
            }
            .hrItem {
                border: none;
                height: 1px;
                /* Set the hr color */
                color: #333; /* old IE */
                background-color: #fff; /* Modern Browsers */
            }

            table {
                border-collapse: collapse;
                width: 100%;
                border: solid 2px gray;
            }

            th, td {
                text-align: left;
                padding: 8px;
            }

            tr:nth-child(even){background-color: #f2f2f2}

            th {
                background-color: #535454;
                color: white;
            }  
    </style>
    </head>
    <body>
        <h1> Internet Banking </h1>
        <hr> </hr>
        <h3> Consulta de cuentas </h3>
        <h4> Usuario: {{nombre}} {{apellido}}</h4>
        <h4> Fecha: {{Fecha|date:"F d, Y"}} </h4>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Número de Cuenta</th>
                    <th>Tipo de Cuenta</th>
                    <th>Balance Disponible</th>
                </tr>
            </thead>
            <tbody>
                {% for account in accounts %}
                    <tr>
                        <td>-</td>
                        <td  style="text-align:right;"> {{ account.NumeroCuenta }} </td>
                        <td  style="text-align:right;"> {{ account.Tipo }} </th>
                        <td  style="text-align:right;"> {{ account.Saldo }} </th>
                    </tr>
                {% endfor %}
            </tbody>
                <tr style="background-color: #729371">
                    <td colspan="3"> Total </td>
                    <td style="background-color:#9b5d51; font-weight: 900;">Balance Total</td>
                </tr>
                <!-- Aqui se despliegan los totales -->
                <tr>
                    <td colspan="4" style="text-align:right; text-decoration: underline; font-weight: 900;">{{ total_balances }}</td>
                </tr>
        </table>
    </body>
</html>

django/core/templates/core/pdf_historial.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Consulta de cuentas </title>
        <style type="text/css">
            body {
                font-weight: 200;
                font-size: 14px;
            }
            .header {
                font-size: 20px;
                font-weight: 100;
                text-align: center;
                color: #007cae;
            }
            .title {
                font-size: 22px;
                font-weight: 100;
               /* text-align: right;*/
               padding: 10px 20px 0px 20px;  
            }
            .title span {
                color: #007cae;
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                /*margin-left: 40%;*/
            }
            .hrItem {
                border: none;
                height: 1px;
                /* Set the hr color */
                color: #333; /* old IE */
                background-color: #fff; /* Modern Browsers */
            }

            table {
                border-collapse: collapse;
                width: 100%;
                border: solid 2px gray;
            }

            th, td {
                text-align: left;
                padding: 8px;
            }

            tr:nth-child(even){background-color: #f2f2f2}

            th {
                background-color: #535454;
                color: white;
            }  
    </style>
    </head>
    <body>
        <h1> Internet Banking </h1>
        <hr> </hr>
        <h3> Consulta de cuentas </h3>
        <h4> Usuario: {{nombre}} {{apellido}}</h4>
        <h4> Fecha: {{Fecha|date:"F d, Y"}} </h4>
        <h3> Total de cuentas con transacciones: {{ totalmovs }}  </h3>
        {% for key, value in accounts.items %}
        <p> Cuenta: <span class="badge badge-secondary">{{ key }}</span></p>
    
        <table class="table table-striped">
          <thead>
            <th>Cuenta emisor</th>
            <th>Cuenta receptor</th>
            <th>Tipo de movimiento</th>
            <th>Monto</th>
            <th>Banco</th>
          </thead>
          <tbody>
            {% for movement in value %}
            <tr>
              <td>{{ movement.CuentaEmisor }}</th>
              <td>{{ movement.CuentaReceptor }}</th>
              <td>{{ movement.tipoMovimiento }}</th>
              <td>{{ movement.Monto }}</th>
              <td>{{ movement.Banco }}</th>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    {% endfor %}
    </body>
</html>

django/core/templates/core/transactions.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Realizar transaccion{% endblock title %}

{% block body %}
  <h1>Realizar transaccion</h1>

    {% if message %}
    <div class="alert alert-success" role="alert">{{ message }}</div>
  {% endif %}

  <form method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" class="btn btn-primary" value="Realizar transacccion">
  </form>
{% endblock body %}