django/config/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

django/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
import core.urls
import user.urls
from user import views as user_views
from core.views import GeneratePdf, GeneratePdfHistorial

#con urlpatterns podemos mappear las urls de la pagina con sus respectivas vistas
urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(user.urls, namespace='user')),
    path('user/', include('django.contrib.auth.urls')),
    path('', include(core.urls, namespace='core')),
    
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        user_views.activate, name='activate'), #para el link de validacion del email

    path('pdf/consultas/', GeneratePdf.as_view(), name='get-pdf-consulta'),
    path('pdf/historial/', GeneratePdfHistorial.as_view(), name='get-pdf-historial'),
]

django/core/urls.py
from django.urls.conf import path
from core import views

app_name = 'core'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('history', views.MovementHistoryView.as_view(), name='mov_history'),
    path('accounts', views.CheckAccounts.as_view(), name='check_accounts'),
    path('transaction/new', views.TransactionView.as_view(), name='make_transaction'),
]

django/user/urls.py
from django.contrib.auth.views import LogoutView, LoginView #Dejaremos que django se haga cargo de las vistas para el manejo del
#login y el logout del usuario.
from django.urls import path
from user import views

app_name = 'user'
urlpatterns = [
    path('login', LoginView.as_view(), name="login"), #LoginView.as_view() es una vista que proporciona django
    path('logout', LogoutView.as_view(), name="logout"), #LogoutView.as_view() es una vista que proporciona django
    path('register', views.registrationFormExtended, name="register"),
    path('edit', views.edit_user_info, name="edit"),
]

django/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Start 3rd Party CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- End 3rd Party CSS -->
  <link rel="stylesheet" href="{% static 'main.css' %}">

  <title>{% block title %}Bank app{% endblock title %}</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-light">
      <a href="{% url 'core:home' %}">Bank App</a>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item"><a href="{% url 'user:logout' %}" class="nav-link">Logout</a></li>
          <li class="nav-item"><a href="{% url 'user:edit' %}" class="nav-link">Edit info</a></li>
        {% else %}
          <li class="nav-item"><a href="{% url 'user:login' %}" class="nav-link">Login</a></li>
          <li class="nav-item"><a href="{% url 'user:register' %}" class="nav-link">Register</a></li>
        {% endif %}
    </div>
  </nav>
  <div class="container">
    {% block body %}{% endblock %}
  </div>

  <!-- Start 3rd Party JS -->
  <script
  src="https://code.jquery.com/jquery-1.12.4.min.js"
  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
  crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  <!-- End 3rd Party JS -->
</body>
</html>